FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY run_api.py .
COPY api_avicola/ ./api_avicola/

EXPOSE 5000

CMD ["python", "run_api.py"]
